### ISSUE TITLE
TODO List 1

### ISSUE THREAD

**Issue by dkanafeev** [dkanafeev/action-labeling-road-defects#1]
should be done by 05/08
- [ ] дополнительная фильтрация входных данных (необходимость изучается)
- [x] Разработка шаблона для отображения + чтение данных
- [x] отображение графиков
- [x] отображение видео
- [x] отображение карты с данными о положении
- [x] Воспроизведение, остановка, перемотка с синхронизацией между окнами
- [x] разметка данных и запись в файл
- [x] привязка видео к данным по времени (ручная)

Удалено:
- последовательное чтение данных с учетом времени - нет особой необходимости на данный момент из-за небольшого размера файлов
- перерасчет данных акселерометра - добавлено в data-collector
- перемотка - фактически дублирует изменение скорости воспризведения
- привязка местоположения к данным по времени - нет необходимости, данные из всех источников записываются в файл относительно времени запуска программы
